spring:
  datasource:
    url: jdbc:postgresql://postgres:zGApFEIpFjGNlbfdyyaDfBNVGqVqhiib@:5432/railway
    username: postgres
    password: zGApFEIpFjGNlbfdyyaDfBNVGqVqhiib
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create