spring:
  datasource:
    url: jdbc:postgresql://postgres:OCGtavmhUeSweKkqoIHylMOZZcLJxLAf@roundhouse.proxy.rlwy.net:12400/railway
    #url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop